#!/usr/bin/env bash
set -e

# ==============================================================================
# OpenClaw Always Free Master Setup v1.1 - Interactive Installer
# ==============================================================================

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}Starting OpenClaw Master Setup v1.1...${NC}"

# ------------------------------------------------------------------------------
# Phase 1: Pre-flight Checks
# ------------------------------------------------------------------------------
check_privileges() {
    if [ "$EUID" -ne 0 ]; then
        echo -e "${RED}Please run as root or with sudo.${NC}"
        exit 1
    fi
}

check_os() {
    if ! grep -q "Ubuntu\|Debian" /etc/os-release; then
        echo -e "${YELLOW}Warning: This script is tested on Ubuntu/Debian. Proceed with caution.${NC}"
    fi
}

check_network() {
    if ! ping -c 1 8.8.8.8 &> /dev/null; then
        echo -e "${RED}Network connection failed. Please check your internet.${NC}"
        exit 1
    fi
}

check_resources() {
    # Check RAM (min 2GB)
    TOTAL_RAM=$(free -m | awk '/^Mem:/{print $2}')
    if [ "$TOTAL_RAM" -lt 1900 ]; then
        echo -e "${YELLOW}Warning: Less than 2GB RAM detected. OpenClaw might run out of memory.${NC}"
    fi
    # Check Disk Space (min 10GB free on /)
    FREE_DISK=$(df -m / | awk '/\//{print $4}')
    if [ "$FREE_DISK" -lt 10000 ]; then
        echo -e "${YELLOW}Warning: Less than 10GB free disk space. Deployments might fail.${NC}"
    fi
}

check_packages() {
    echo "Installing required dependencies..."
    apt-get update -qq
    apt-get install -qq -y curl git jq unzip build-essential wget sudo
}

echo "Performing system checks..."
check_privileges
check_os
check_network
check_resources
check_packages
echo -e "${GREEN}System checks passed.${NC}"

# ------------------------------------------------------------------------------
# Phase 2: Interactive Wizard
# ------------------------------------------------------------------------------
prompt_with_masking() {
    local prompt="$1"
    local var_name="$2"
    local allow_skip="$3"
    
    while true; do
        echo -e "\n${YELLOW}${prompt}${NC}"
        if [ "$allow_skip" = true ]; then
            echo "(Press Enter to skip, type 'quit' to exit)"
        fi
        
        read -s -p "> " input_val
        echo ""
        
        if [ "$input_val" = "quit" ]; then
            echo -e "${RED}Exiting installer.${NC}"
            exit 0
        fi
        
        if [ -z "$input_val" ]; then
            if [ "$allow_skip" = true ]; then
                eval "$var_name=''"
                break
            else
                echo -e "${RED}Value is required. Type 'quit' to exit.${NC}"
                continue
            fi
        fi
        
        eval "$var_name=\"\$input_val\""
        break
    done
}

echo -e "\n${GREEN}=== OpenClaw Configuration Wizard ===${NC}"

prompt_with_masking "Enter Gemini API Key:" GEMINI_API_KEY true
prompt_with_masking "Enter OpenRouter API Key:" OPENROUTER_API_KEY true
prompt_with_masking "Enter NVIDIA NIM API Key:" NVIDIA_NIM_API_KEY true
prompt_with_masking "Enter Exa API Key:" EXA_API_KEY true
prompt_with_masking "Enter Telegram Bot Token:" TELEGRAM_BOT_TOKEN true

echo -e "\n${YELLOW}Enter Telegram Chat ID:${NC}"
echo "(Press Enter to skip, type 'quit' to exit)"
read -p "> " TELEGRAM_CHAT_ID

if [ "$TELEGRAM_CHAT_ID" = "quit" ]; then
    exit 0
fi

# ------------------------------------------------------------------------------
# Phase 3: Automatic Environment Generation
# ------------------------------------------------------------------------------
echo -e "\n${GREEN}Generating Environment Configuration...${NC}"

cat <<EOF > .env
# Auto-generated by OpenClaw Installer
GEMINI_API_KEY=${GEMINI_API_KEY}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
NVIDIA_NIM_API_KEY=${NVIDIA_NIM_API_KEY}
EXA_API_KEY=${EXA_API_KEY}
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
ENVIRONMENT=production
EOF

chmod 600 .env
echo -e "${GREEN}Created .env file with appropriate permissions.${NC}"

# Prepare configs dir
mkdir -p configs
cp templates/secrets-template.env configs/.env.backup 2>/dev/null || true

# Generate default configuration if doesn't exist
if [ ! -f configs/model-routing.json ]; then
    cp configs/model-routing.example.json configs/model-routing.json 2>/dev/null || echo "{}" > configs/model-routing.json
fi

if [ ! -f configs/openclaw-alwaysfree.json ]; then
    cp configs/openclaw-alwaysfree.example.json configs/openclaw-alwaysfree.json 2>/dev/null || echo "{}" > configs/openclaw-alwaysfree.json
fi

# ------------------------------------------------------------------------------
# Delegate to specialized scripts
# ------------------------------------------------------------------------------
echo -e "\n${GREEN}Executing Phase 4: Docker Automation...${NC}"
bash scripts/setup_docker.sh

echo -e "\n${GREEN}Executing Phase 5: OpenClaw Deployment...${NC}"
bash scripts/deploy_openclaw.sh

echo -e "\n${GREEN}Executing Phase 6: Systemd Automation...${NC}"
bash scripts/setup_systemd.sh

echo -e "\n${GREEN}Executing Phase 7: Monitoring...${NC}"
bash scripts/setup_monitoring.sh

echo -e "\n${GREEN}Executing Phase 8: Backup System...${NC}"
bash scripts/setup_backup.sh

echo -e "\n${GREEN}Executing Phase 9: Health Verification...${NC}"
bash scripts/verify_install.sh

echo -e "\n${GREEN}======================================================${NC}"
echo -e "${GREEN}OpenClaw Master Setup completed successfully!${NC}"
echo -e "${GREEN}View your installation report in reports/install-report.md${NC}"
echo -e "${GREEN}======================================================${NC}"
